feat: добавлен весь функционал спринта #9
na1mov/java-filmorate pull request #1
Opened 2023-01-19 11:10 UTC by na1mov

2023-01-19 18:13 UTC, ohelly requested changes
Привет! Отличная работа, все сделано на высшем уровне. У меня нет замечаний, есть только несколько рекомендаций, которые выполнять не обязательно.

2023-01-19 18:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +package ru.yandex.practicum.filmorate.service;
Здорово, что создан сервисный слой!

2023-01-19 18:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Рекомендация: Для идентификаторов лучше использовать классы обертки(Long, Integer), так как они могут быть null, а примитивный int - нет.

Также для полей классов-моделей обычно не используют final модификатор, так как их значения могут меняться в процессе выполнения и это нормально.

Данная рекомендация также относится к классу User.

2023-01-19 18:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void checkFilm(Film film) {
Рекомендация: У нас уже настроена валидация с помощью аннотаций в классе-моделе, поэтому нет необходимости проверять снова, данные проверки ведь происходят в контроллере при запросах.

Рекомендация также относится и к UserService.

2023-01-19 18:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, Month.DECEMBER, 28))) {
Рекомендация: Для данной проверки можно создать собственную аннотацию и повесить над полем в классе Film. Будет отличной практикой.

2023-01-21 11:13 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +package ru.yandex.practicum.filmorate.service;
Спасибо, подумал, что лучше разделить эту логику на два слоя)

2023-01-21 11:14 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Исправил, изначально хотел тоже обёртки использовать, но на автомате прописал int

2023-01-21 12:35 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void checkFilm(Film film) {
Изначально сделал задание не через аннотации, решил оставить, чтоб было видно проделанную работу) исправил

2023-01-21 12:36 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, Month.DECEMBER, 28))) {
Разобрался с самописными аннотациями, вроде ничего сложного на первый взгляд. сделал проверку на дату релиза

2023-01-22 09:28 UTC, ohelly approved these changes
Все супер! Работу принимаю

2023-01-22 09:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmEraValidator.java
> +        return localDate.isAfter(LocalDate.of(1895, Month.DECEMBER, 28));
Рекомендация: Будет лучше если добавить проверку даты на null, так как аннотация ``@NotNull`` в классе Film может отработать после этой.

2023-01-23 16:10 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmEraValidator.java
> +        return localDate.isAfter(LocalDate.of(1895, Month.DECEMBER, 28));
Понял, добавлю в следующем спринте, а этот pull request можно мержить?)

2023-01-26 05:25 UTC, merged