feat: добавлен весь функционал спринта #10
na1mov/java-filmorate pull request #2
Opened 2023-01-26 16:51 UTC by na1mov

2023-01-27 19:07 UTC, ohelly requested changes
Привет! Отличная работа, в целом все супер. Есть одно замечание, не критическое, но про него указано в ТЗ. Также оставил ряд рекомендаций, на которые стоит обратить внимание.

2023-01-27 19:07 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +public interface FilmStorage {
Необходимо исправить: По ТЗ необходимо добавить метод удаления и реализовать его в соответствующем классе.

Справедливо и для UserStorage.

2023-01-27 19:07 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Рекомендация:
1) Предлагаю переименовать немного эксепшены. То, за что сейчас отвечает ValidationException больше похоже не на ошибку валидации, а на то, что запись не найдена - это уже FilmNotFoundException, или просто NotFoundException и тогда ее можно будет применить и к юзерам. А в случаях, когда сейчас используется IncorrectParameterException как раз похож на ValidationException. В ErrorHandler тогда тоже все будет корректно NotFoundException -> возвращаем 404 статус, что является Not Found. ValidationException -> возвращаем 400, что является BadRequest ошибка во входных данных.

2) Также предлагаю в методах получения User'a или Film'a по идентификатору не выкидывать ексепшен, а возвращать null, а вот уже в классе-сервисе этот null обрабатывать и выкидывать ошибку. Это из-за того, что не всегда бывают ситуации, что нужно выкидывать ошибку, иногда нужно достать элемент, а если его нет то создать(как пример). Либо конечно можно создать 2 метода, один выкидывает ошибку, другой возвращает null, но тут уже дело вкуса :) 

Также относится и к UserStorage.

2023-01-27 19:07 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
Рекомендация: Чтобы каждый раз не писать конструктор с инъекцей всех необходимых бинов, можно использовать аннотацию ломбока ``@RequiredArgsConstructor``, она сгенерит конструктор для всех final полей класса.

2023-01-27 19:07 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilms() == null || filmStorage.getFilms().isEmpty()) {
Рекомендация: Предлагаю операцию ``filmStorage.getFilms()`` вынести в отдельную переменную и проверять уже ее на null и empty. Сейчас получается так, что мы ходим в хранилище 2 раза за одними и теми же данными.

2023-01-29 08:11 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +public interface FilmStorage {
Проглядел, что надо добавить возможность удаления, теперь добавил

2023-01-29 08:15 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
Исправил

2023-01-29 08:17 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilms() == null || filmStorage.getFilms().isEmpty()) {
Исправил

2023-01-29 09:06 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +public interface FilmStorage {
Странно, что тесты в Postman не проверяют удаление пользователей и фильмов)

2023-01-29 09:12 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
1. Я руководствовался точно той же логикой, когда делал задание спринта. :)  Изначально сделал 2 новых класса исключений UserNotFoundException и FilmNotFoundException, и также думал в следующем спринте унифицировать это дело в просто NotFoundException, но тесты на github эти классы не смогли пройти, хотя были сделаны нормально(можно посмотреть во втором коммите этого спринта, где я их заменил на ValidationException). Сейчас попробую ещё раз в унифицированным классом NotFoundException, может с ним повезёт.)
2. Сделано

2023-01-29 09:19 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
![image](https://user-images.githubusercontent.com/73291118/215316982-a19a6eff-1333-4941-8bc4-4ff8f7895433.png)

2023-01-29 09:20 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Опять тоже самое, видимо тесты хотят, чтоб всё прокидывалось через ValidationException, увы)

2023-01-29 12:27 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
![image](https://user-images.githubusercontent.com/73291118/215326087-a6bd45d6-5c31-4770-ab38-0b8707a10558.png)

2023-01-29 12:28 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
А тут получается надо, чтоб выкидывалось именно ValidationException?

2023-01-29 12:47 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
В итоге по этим двум пунктам пришлось вернуть всё так, как было изначально мной сделано, я конечно пытался сделать так, как ты советовал, пробовал разные варианты, но тесты хотят именно 404 not found на validation исключении и всё тут, вынес проверку в отдельный метод, чтоб смотрелось получше. Про мусор в классе UserService в виде проверок на null (которые остались от попыток) знаю, приберусь в след спринте, в этом и так уже слишком много коммитов... Рекомендация хорошая, а вот тесты весёлые... Жаль день убил на эту игру с "валидатором"...

2023-01-30 13:25 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Да, что-то о тестах то я не подумал) Думал там нет такой жестки привязки эксепшенам...

2023-01-30 13:25 UTC, ohelly approved these changes
Все супер! Работу принимаю. Удачи в дальнейшем обучении!

2023-02-09 08:33 UTC, merged