feat: добавлен весь функционал спринта #11
na1mov/java-filmorate pull request #3
Opened 2023-02-17 12:20 UTC by na1mov

Добавлен весь функционал спринта #11:
11.1 добавлена и проверена p2p ER-диаграмма, но хотел бы также услышать фидбек от ревьюера, готов пожертвовать одной проверкой
11.2 просто всё сделано :)

2023-02-18 13:14 UTC, ohelly requested changes
Привет! В целом отличная работе, в общем как и всегда :) Но есть несколько замечаний, которые необходимо исправить. Также оставил ряд рекомендаций.

По поводу диаграммы - у меня к ней вопросов нет, все сделано прекрасно!

2023-02-18 13:14 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            film.getGenres().stream()
Рекомендация: Сейчас на каждую вставку жанра выполняется отдельный запрос, что не есть хорошо. Рекомендую изучить такую штуку как batchUpdate, вставка сразу нескольких записей.

2023-02-18 13:14 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setGenres(new HashSet<>(getFilmGenres(film.getId())));
Необходимо исправить: Будет правильнее, если жанры мы будем получать из FilmService. То есть, в классе GenreDbStorage создадим соответствующие методы, которые будем вызывать из FilmService. Также сейчас при получении всех фильмов, на каждый фильм выполняется свой запрос на получение жанров, то есть на N фильмов приходится N запросов жанров, от этого необходимо избавиться и получать все жанры одним запросом вне зависимости от кол-ва фильмов.

2023-02-18 13:14 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setMpa(mpaRatingDbStorage.getMpaRating(resultSet.getInt("rating_mpa_id")));
Рекомендация: Рейтинг можно получать с помощью джойна в запросе получения фильма.

2023-02-18 13:14 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private void addFilmGenres(Film film) {
Рекомендация: Методы updateFilmGenres и addFilmGenres в целом можно объединить в один, так как они почти ничем не отличаются и назвать например saveGenres

2023-02-18 13:14 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlQuery = "INSERT INTO film_like (film_id, user_id) VALUES(?, ?)";
Необходимо исправить: Добавляется лайк, но в сервисе нет проверки на то, что фильм и юзер сущестсвуют.

Аналогично и при удалении лайка

2023-02-18 13:14 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.addFriend(userId, friendId);
Необходимо исправить: При добавлении в друзья необходимо проверять, существуют ли оба пользователя в базе.

Аналогично и при удалении из друзей.

2023-02-18 13:14 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getFriends(userId);
Необходимо исправить: При получении друзей тоже необходимо проверять, существует ли пользователь в базе.

Аналогично и при получении общих друзей.

2023-02-19 07:22 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.addFriend(userId, friendId);
Проверка на наличие пользователя, который добавляет в друзья, у меня была, добавил проверку на наличие пользователя, которого добавляют, обе проверки находятся в UserDbStorage, т.к. взаимодействуют с базой и выносить их в сервис как будто нет смысла.

2023-02-19 07:24 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getFriends(userId);
Сначала думал добавить проверку на наличие пользователей в sql запрос, но в итоге реализовал проверки отдельным запросом, т.к. только в таком случае можно прокинуть исключение с нужным ID, чтоб у пользователя было понимание, в чём он ошибся.

2023-02-19 07:46 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlQuery = "INSERT INTO film_like (film_id, user_id) VALUES(?, ?)";
Проверка на наличие фильма была реализована в обоих методах, подправил её немного, добавил проверку на наличие пользователя. Все проверки реализованы не в FilmService, а в FilmDbStorage, т.к. именно он взаимодействует с базой данных. Где кидать ошибку, если не там? В прошлом спринте я уже пробовал перенести проброс исключений в сервис, тесты были против.

2023-02-19 07:55 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private void addFilmGenres(Film film) {
Оставил два метода, но повторяющуюся часть объединил в один

2023-02-19 10:53 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setGenres(new HashSet<>(getFilmGenres(film.getId())));
Исправил:
- перенёс запросы жанров в GenreDbStorage
- добавил поиск сразу всех жанров для одного фильма
- добавил поиск всех жанров для всех фильмов

2023-02-19 12:49 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            film.getGenres().stream()
Изучил, обновил, также перенёс оба метода работающие с жанрами в GenreDbStorage

2023-02-19 13:53 UTC, na1mov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setMpa(mpaRatingDbStorage.getMpaRating(resultSet.getInt("rating_mpa_id")));
Исправил

2023-02-20 18:05 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, удачи в дальнейшем обучении!

2023-02-20 18:05 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setLikes(new HashSet<>(getFilmLikes(film.getId())));
Рекомендация: Для лайков тоже можно будет сделать один запрос для всех фильмов, как сейчас с жанрами, но это уже не обязательно)

2023-02-20 18:05 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +    public Film getFilmGenres(Film film) {
Рекомендация: В целом, можно данный метод удалить и оставить только getFiilmsGenres, который получает жанры для нескольких фильмов. И тогда, если нам нужно будет достать жанры только для одного фильма, то можем положить его в коллекцию: ``List.of(film)`` и метод getFiilmsGenres прекрасно справится со своей задачей.

2023-02-22 10:10 UTC, merged